version: "3"

services:
  app:
    build: ./
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: yourprojectdomain.com
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: yourprojectdomain.com
      LETSENCRYPT_EMAIL: email@yourprojectdomain.com
networks:
  default:
    external:
      name: nginx-proxy